Added Quiz Pages in C/CPP/Js/Django Pages
arpit456jain/CodingEasy pull request #414
Opened 2022-05-27 12:56 UTC by nikhil25803

## 👨‍💻 Changes proposed
This Pll request is regarding the issue #412 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Added Quiz pages in C, Cpp, Js, and Django pages. With a dynamic result page with solutions

## 📷 Screenshots
[![image](https://www.linkpicture.com/q/quizCPP.png)](https://www.linkpicture.com/view.php?img=LPic6290c99e512fd1290705484)

2022-05-27 12:58 UTC, nikhil25803 commented
@singhmansi25 , @raghavTinker , @KKhushhalR2405 ... Review it once pls :)

2022-05-27 18:05 UTC, KKhushhalR2405 requested changes
![image](https://user-images.githubusercontent.com/58569950/170766263-c0bbcef4-a5c9-4c42-bc26-6a733df5e421.png)
The answers are pre-marked. Please check it out.

2022-05-27 18:26 UTC, nikhil25803 commented
@KKhushhalR2405 Bhaiya... I tried it with JS but that's not possible because of the looping structure of the templates. I told @singhmansi25 Di and @arpit456jain Bhaiya about this issue, and they said it's okay. (The same problem was in the Python quiz too).

2022-05-28 03:27 UTC, singhmansi25 approved these changes

2022-05-28 04:22 UTC, merged